name: PageDewarp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - notebook
  - jupyterlab
  - ipykernel
  - ipywidgets
  - numpy
  - pandas
  - matplotlib
  - opencv
  - pillow
  - pip:
      - transformers
      - datasets
      - pytesseract
      - scikit-image